### ISSUE TITLE
RE: Porting this sysfs Library to a BBB...

### ISSUE THREAD

**Issue by silver2row** [embeddedarm/gpio-sysfs-demo#2]
Hello,

I am using a Linux SBC and I am a bit unfamiliar with the C Language. Would I just change the gpio userspace locations on the lib or would I change the internals found in the Linux SBC to fit the lib?

...

I can probably do either/neither/both but I figured if someone would know, it would be the owner of the repo.

Seth

P.S. I know it is three years old and things have changed somewhat. If you find time and have time, please do contact me.

**Comment by ts-kris** [comment]
A few things to note here:

1. This library is written targeting Technologic Systems' product line. While this will likely work on other ARM based platforms, it may not work on devices such as the Beagle Bone Black which is on the "bleeding edge" of kernel development due to how things have recently changed in the kernel. 
2. As of some point in the 4.x kernel series, the sysfs GPIO interface was deprecated in favor of gpiod/libgpiod. This is likely what the BBB uses, you may want to find a support forum for the BBB specifically. Note that sysfs GPIO interface is slated to be completely removed from the kernel in the near future. So even if this library would work for your application, I wouldn't recommend using it if you are tracking upstream kernel.
3. If the BBB is in fact still able to use sysfs GPIO, then the library would likely work as-is. So long as you use the correct GPIO numbers. The sysfs interface is a flat numbered space of GPIOs, if it exists and is functional, then the kernel should map every GPIO to this space. Our demo/library does not limit this space, and any arbitrary number should be able to be used.

**Comment by silver2row** [comment]
Thank you.
